### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by CeccoCQ** [paulo-raca/gradle-plugins#1]
Please, add an example that illustrates how it works.

**Comment by paulo-raca** [comment]
I'll add an example when I have the time.

In the meantime, It'ss pretty simple: Just paste this in your build.gradle and everything works:

```
plugins {
  id "com.inutilfutil.android-resource-placeholder" version "1.0.3"
}
```

**Comment by paulo-raca** [comment]
A test/sample was included on the source
